apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubexecutor
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubexecutor
  template:
    metadata:
      labels:
        app: kubexecutor
    spec:
      containers:
        - name: kubexecutor
          image: musiek/kubexecutor:latest
          ports:
            - containerPort: 8080