apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediator
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediator
  template:
    metadata:
      labels:
        app: mediator
    spec:
      runtimeClassName: kata-dragonball
      containers:
        - name: mediator
          image: musiek/mediator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: HTTP_PORT
              value: 8081
            - name: RUNNER_POD_NAME
              value: runner
            - name: RUNNER_INSTANCES
              value: 10
            - name: PATH_FORMAT
              value: "http://%s.runner-svc.app.svc.cluster.local:8080"
            - name: STATUS_QUERY_PERIOD
              value: 2000
            - name: HTTP_DOMAIN
              value: "https://kube.skni.edu.pl"
          envFrom:
            - secretRef:
                name: mediator-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
---
apiVersion: v1
kind: Service
metadata:
  name: mediator
  namespace: app
  labels:
    app: mediator
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: mediator
---
apiVersion: v1
kind: Service
metadata:
  name: mediator-lb
  namespace: app
  labels:
    app: mediator
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4748
      targetPort: 8081
  selector:
    app: mediator