apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: musiek/runner
    newTag: '0.20'
  - name: musiek/mediator
    newTag: '0.24'
  - name: musiek/frontend
    newTag: '0.02'

replicas:
  - name: runner
    count: 10
