apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: musiek/runner
    newTag: '0.22'
  - name: musiek/mediator
    newTag: '0.26'
  - name: musiek/frontend
    newTag: '0.03'

replicas:
  - name: runner
    count: 10
