apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: musiek/runner
    newTag: '0.15'
  - name: musiek/mediator
    newTag: '0.2a'

replicas:
  - name: runner
    count: 10