apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: musiek/runner
    newTag: '0.17'
  - name: musiek/mediator
    newTag: '0.21'
  - name: musiek/frontend
    newTag: '0.01'

replicas:
  - name: runner
    count: 10
