name: Build & Push Front

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get runner version
      run: echo "IMAGE_TAG=$(./yq '.images[2].newTag' k8s/overlays/dev/kustomization.yaml)" >> $GITHUB_ENV
    
    - name: Build Docker image
      working-directory: ./front
      run: docker build -t musiek/front:${{ env.IMAGE_TAG }} -t musiek/front:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push musiek/front:${{ env.IMAGE_TAG }}
        docker push musiek/front:latest
