name: Build & Push Mediator

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag'
        required: true
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mediator
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew jar

    - name: Build Docker image
      run: docker build -t musiek/mediator:${{ github.event.inputs.imageTag }} -t musiek/mediator:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push musiek/mediator:${{ github.event.inputs.imageTag }}
        docker push musiek/mediator:latest
